"""Made content.required_priv_level required

Revision ID: 10e1388006e
Revises: 5491d450b91
Create Date: 2015-05-20 11:34:55.124373

"""

# revision identifiers, used by Alembic.
revision = '10e1388006e'
down_revision = '5491d450b91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'required_priv_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'required_priv_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
