"""empty message

Revision ID: 1caff18b309
Revises: 25623db4b6f
Create Date: 2015-05-19 23:39:28.568333

"""

# revision identifiers, used by Alembic.
revision = '1caff18b309'
down_revision = '25623db4b6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('data_blob', sa.Text(), nullable=False))
    op.alter_column('content', 'content_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'content', 'member', ['created_by'], ['id'])
    op.create_foreign_key(None, 'content', 'member', ['edited_by'], ['id'])
    op.drop_column('content', 'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.alter_column('content', 'content_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('content', 'data_blob')
    ### end Alembic commands ###
