"""empty message

Revision ID: 2409d465579
Revises: None
Create Date: 2015-05-23 23:09:52.287559

"""

# revision identifiers, used by Alembic.
revision = '2409d465579'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.Text(), nullable=False),
    sa.Column('longname', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('key', sa.String(length=250), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.CHAR(length=9), nullable=True),
    sa.Column('primary_club', sa.Integer(), nullable=False),
    sa.Column('assigned_team', sa.Integer(), nullable=True),
    sa.Column('priv_level', sa.Integer(), nullable=False),
    sa.Column('pw_hash', sa.Text(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('name_first', sa.Text(), nullable=False),
    sa.Column('name_middle', sa.Text(), nullable=False),
    sa.Column('name_last', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('texting_ok', sa.Boolean(), nullable=True),
    sa.Column('email1', sa.Text(), nullable=False),
    sa.Column('email2', sa.Text(), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('acad_standing', sa.Text(), nullable=True),
    sa.Column('acad_major', sa.Text(), nullable=True),
    sa.Column('acad_minor', sa.Text(), nullable=True),
    sa.Column('acad_conc', sa.Text(), nullable=True),
    sa.Column('acad_grad_qtr', sa.Text(), nullable=True),
    sa.Column('signup_date', sa.DateTime(), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('paid_until_date', sa.DateTime(), nullable=True),
    sa.Column('receipt_date', sa.DateTime(), nullable=True),
    sa.Column('badge_type', sa.Integer(), nullable=True),
    sa.Column('shirt_size', sa.Text(), nullable=True),
    sa.Column('shirt_received_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email1'),
    sa.UniqueConstraint('email2'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('render_template', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('edited_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('required_priv_level', sa.Integer(), nullable=False),
    sa.Column('show_in_nav', sa.Integer(), nullable=False),
    sa.Column('data_blob', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['member.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('hosting_club', sa.Integer(), nullable=True),
    sa.Column('presenter', sa.Text(), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('shorturl', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('location_type', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('content_block_id', sa.Integer(), nullable=True),
    sa.Column('rsvp_max_replies', sa.Integer(), nullable=True),
    sa.Column('rsvp_allow_maybe', sa.Boolean(), nullable=False),
    sa.Column('rsvp_allow_comments', sa.Boolean(), nullable=False),
    sa.Column('rsvp_public_view', sa.Boolean(), nullable=False),
    sa.Column('rsvp_send_reminder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_block_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['hosting_club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shorturl')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_block_id', sa.Integer(), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_block_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['leader'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.ForeignKeyConstraint(['member'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projectmembership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['member.id'], ),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('reply', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.ForeignKeyConstraint(['member'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvp')
    op.drop_table('projectmembership')
    op.drop_table('attendance')
    op.drop_table('project')
    op.drop_table('event')
    op.drop_table('content')
    op.drop_table('member')
    op.drop_table('sessions')
    op.drop_table('club')
    ### end Alembic commands ###
