"""empty message

Revision ID: 25623db4b6f
Revises: 31dcd0ce343
Create Date: 2015-05-19 20:00:48.982254

"""

# revision identifiers, used by Alembic.
revision = '25623db4b6f'
down_revision = '31dcd0ce343'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'testing')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('testing', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
