"""Created Event table, modified Member table.

Revision ID: 2f4b2799e06
Revises: 1caff18b309
Create Date: 2015-05-19 23:49:08.376552

"""

# revision identifiers, used by Alembic.
revision = '2f4b2799e06'
down_revision = '1caff18b309'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('hosting_club', sa.Integer(), nullable=True),
    sa.Column('presenter', sa.Text(), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('shorturl', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('location_type', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('content_block_id', sa.Integer(), nullable=True),
    sa.Column('rsvp_max_replies', sa.Integer(), nullable=True),
    sa.Column('rsvp_allow_maybe', sa.Boolean(), nullable=False),
    sa.Column('rsvp_allow_comments', sa.Boolean(), nullable=False),
    sa.Column('rsvp_public_view', sa.Boolean(), nullable=False),
    sa.Column('rsvp_send_reminder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_block_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['hosting_club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shorturl')
    )
    op.add_column('member', sa.Column('primary_club', sa.Integer(), nullable=False))
    op.drop_constraint('member_club_fkey', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'club', ['primary_club'], ['id'])
    op.drop_column('member', 'club')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('club', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_club_fkey', 'member', 'club', ['club'], ['id'])
    op.drop_column('member', 'primary_club')
    op.drop_table('event')
    ### end Alembic commands ###
