"""empty message

Revision ID: 31dcd0ce343
Revises: fa1f64a341
Create Date: 2015-05-19 19:49:56.130186

"""

# revision identifiers, used by Alembic.
revision = '31dcd0ce343'
down_revision = 'fa1f64a341'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('testing', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'testing')
    ### end Alembic commands ###
