"""Created Project table

Revision ID: 3339701b09e
Revises: 179dbf8e532
Create Date: 2015-05-19 23:58:50.913521

"""

# revision identifiers, used by Alembic.
revision = '3339701b09e'
down_revision = '179dbf8e532'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_block_id', sa.Integer(), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_block_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['leader'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    ### end Alembic commands ###
