"""empty message

Revision ID: 467b37e7995
Revises: None
Create Date: 2015-01-17 12:46:44.349309

"""

# revision identifiers, used by Alembic.
revision = '467b37e7995'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'active',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'ip',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sessions', 'key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sessions', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'valid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sessions', 'valid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sessions', 'key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sessions', 'ip',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sessions', 'active',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###
