"""Converted RSVP table to use a composite primary key

Revision ID: 5491d450b91
Revises: ab9731ece
Create Date: 2015-05-20 00:18:54.213146

"""

# revision identifiers, used by Alembic.
revision = '5491d450b91'
down_revision = 'ab9731ece'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvp')
    op.create_table('rsvp',
    sa.Column('member', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('reply', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.ForeignKeyConstraint(['member'], ['member.id'], ),
    sa.PrimaryKeyConstraint('member', 'event')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvp')
    op.create_table('rsvp',
    sa.Column('member', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reply', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event'], ['event.id'], name='rsvp_event_fkey'),
    sa.ForeignKeyConstraint(['member'], ['member.id'], name='rsvp_member_fkey')
    )
    ### end Alembic commands ###
