"""empty message

Revision ID: ab9731ece
Revises: 3339701b09e
Create Date: 2015-05-20 00:01:55.685720

"""

# revision identifiers, used by Alembic.
revision = 'ab9731ece'
down_revision = '3339701b09e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectmembership',
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['member.id'], ),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project', 'member')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectmembership')
    ### end Alembic commands ###
