"""empty message

Revision ID: fa1f64a341
Revises: None
Create Date: 2015-05-19 19:46:01.139661

"""

# revision identifiers, used by Alembic.
revision = 'fa1f64a341'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('edited_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('required_priv_level', sa.Integer(), nullable=True),
    sa.Column('show_in_nav', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('sessions',
    sa.Column('key', sa.String(length=250), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.Text(), nullable=False),
    sa.Column('longname', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.CHAR(length=9), nullable=True),
    sa.Column('club', sa.Integer(), nullable=False),
    sa.Column('assigned_team', sa.Integer(), nullable=True),
    sa.Column('priv_level', sa.Integer(), nullable=False),
    sa.Column('pw_hash', sa.Text(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('name_first', sa.Text(), nullable=False),
    sa.Column('name_middle', sa.Text(), nullable=False),
    sa.Column('name_last', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('Texting_ok', sa.Boolean(), nullable=True),
    sa.Column('email1', sa.Text(), nullable=False),
    sa.Column('email2', sa.Text(), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('acad_standing', sa.Text(), nullable=True),
    sa.Column('acad_major', sa.Text(), nullable=True),
    sa.Column('acad_minor', sa.Text(), nullable=True),
    sa.Column('acad_conc', sa.Text(), nullable=True),
    sa.Column('acad_grad_qtr', sa.Text(), nullable=True),
    sa.Column('signup_date', sa.DateTime(), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('paid_until_date', sa.DateTime(), nullable=True),
    sa.Column('receipt_date', sa.DateTime(), nullable=True),
    sa.Column('badge_type', sa.Integer(), nullable=True),
    sa.Column('shirt_size', sa.Text(), nullable=True),
    sa.Column('shirt_received_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email1'),
    sa.UniqueConstraint('email2'),
    sa.UniqueConstraint('student_id')
    )
    op.drop_table('test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('member')
    op.drop_table('club')
    op.drop_table('sessions')
    op.drop_table('content')
    ### end Alembic commands ###
